language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "pypy-5.3.1"
  - "pypy3"
matrix:
  include:
    - python: 3.7
      sudo: required
      dist: xenial
install:
  - pip install -U setuptools
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install coveralls
script:
  - coverage run --source=faker setup.py test
after_success:
  - coveralls
