language: python
sudo: false
cache: pip
branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      sudo: required
      dist: xenial
    - python: pypy-5.3.1
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.7
      env: TOXENV=flake8
      sudo: required
      dist: xenial

before_install:
  - pip install pep8
install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
