os: linux
dist: focal
language: python
cache: pip
branches:
  only:
    - master

jobs:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=checkmanifest
    - env: TOXENV=isort
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.7
      env: TOXENV=32bit TEST_32BIT=1
    - python: 3.7
      env: TOXENV=alpine TEST_ALPINE=1

install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
